name: Generate Podcast Feeds
on : [push]
jobs:
  build:
    runs-on : ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-Python@v4
        with:
           python-version: '3.10'
      - name: Install Dependencies
        run: 
          python -m pip install --upgrade pip
          pip install install pyyaml
      - name: Run Feed generator
        run:
          git config user.name github-actions
          git config user.email githubactions@github.com
          git add
          git commit -m "Modified Fedd"
          git Push
  

      
